// 3개의 수에서 제일 큰 수, 제일 작은 수 찾기
// 입력은 prompt()
//prompt로 입력 받은 값은 문자열로 반환 되므로, Number()로 형변환 필요
//  화면 출력은 doucumnet.write()를 사용하면 되고, 출력문 내부에 html 사용 가능





let a = Number(prompt("첫번째 수 입력 : ", ""));
let b = Number(prompt("두번째 수 입력 : ", ""));
let c = Number(prompt("세번째 수 입력 : ", ""));


if(a>b) {
    if(a>c) max = a;
     else max = c;
}

else{
    if(b>c) max=b;
    else max=c;
}

if(a > b) {
    if(b > c) min = c;
    else min = b;
} else {
    if(a > c) min = c;
    else min = a;
}

document.write("<h3>제일 큰 값은 : "+max+ "</h3>");
document.write("<h3>제일 작은 값은 : "+min+ "</h3>");


